# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Porttracker < Formula
  desc "Manage your localhost ports and dev server processes"
  homepage "https://github.com/yusufkaran/porttracker"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yusufkaran/porttracker/releases/download/v0.1.1/porttracker_0.1.1_darwin_amd64.tar.gz"
      sha256 "681403ff3c1ddbf2f1ebd79e8809084e4818a9d89089b4b4d8867ae0fd22b82b"

      define_method(:install) do
        bin.install "pt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yusufkaran/porttracker/releases/download/v0.1.1/porttracker_0.1.1_darwin_arm64.tar.gz"
      sha256 "edae5f32d17212e246dedea8af0d1d0bc635446cabaccb608c210ddc7edb6258"

      define_method(:install) do
        bin.install "pt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yusufkaran/porttracker/releases/download/v0.1.1/porttracker_0.1.1_linux_amd64.tar.gz"
      sha256 "d0e7d459b9ae213647cad2dc52ffc0a42250429d6dee3b5934d5724149c51dc3"
      define_method(:install) do
        bin.install "pt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yusufkaran/porttracker/releases/download/v0.1.1/porttracker_0.1.1_linux_arm64.tar.gz"
      sha256 "c07c4028303903fef2e47b2c39bac3315c28547ebc66c4f2fe1d303106d6db21"
      define_method(:install) do
        bin.install "pt"
      end
    end
  end
end
